project: 
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p99/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p99/
  navbar: 
    logo: IQB-klein.png
    search: true
    left:
      - href: index.qmd
        text: "IQB Testprofil"
    right:
      - icon: github
        href: https://github.com/iqb-vocabs/p99
        aria-label: Source Code


lang: de

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true