---
title: IQB Testprofil
lang: de
---

ID of profile-store: `ptest`

Creator: IQB - Institut zur Qualitätsentwicklung im Bildungswesen

2 Profile definiert:

# Testprofil - Aufgabe

ID of profile: [https://raw.githubusercontent.com/iqb-vocabs/p99/master/unit.json](https://raw.githubusercontent.com/iqb-vocabs/p99/master/unit.json)

| Name/Label | Typ | Parameter | ID Profil-Eintrag |
| :--- | :---: | :--- | :---: |
| Vokabular Aufgabe Dialog | [Vokabular](https://w3id.org/iqb/v34/se/) | url: 'https://w3id.org/iqb/v34/se/', Mehrfachauswahl, Dialogbox | a12 |
| Vokabular Aufgabe In-form | [Vokabular](https://w3id.org/iqb/v34/se/) | url: 'https://w3id.org/iqb/v34/se/', Mehrfachauswahl, integrierte Darstellung | a13 |
| Boolean Aufgabe JA/NEIN | Ja/Nein | Text für WAHR: ja, Text für FALSCH: nein | a3 |
| Number Aufgabe | Zahl | Kommastellen: 0, Mindestwert: 0, Maximalwert: kein | a4 |

: {tbl-colwidths="[15,15,55,15]"}

# Testprofil - Item

ID of profile: [https://raw.githubusercontent.com/iqb-vocabs/p99/master/item.json](https://raw.githubusercontent.com/iqb-vocabs/p99/master/item.json)

| Name/Label | Typ | Parameter | ID Profil-Eintrag |
| :--- | :---: | :--- | :---: |
| Freitext Item A | Text | Einzeilig, Sprache(n): de   | w2 |
| Boolean Item | Ja/Nein | Text für WAHR: störend, Text für FALSCH: nicht relevant | w3 |
| Number Item | Zahl | Kommastellen: 0, Mindestwert: 0, Maximalwert: kein, als Sekunden | w4 |
| Test Vokabular In_form | [Vokabular](https://w3id.org/iqb/v99/pc/) | url: 'https://w3id.org/iqb/v99/pc/', Mehrfachauswahl, Zeige nur erste Ebene, integrierte Darstellung | w5 |
| Test Dialog Vokabular | [Vokabular](https://w3id.org/iqb/v99/sc/) | url: 'https://w3id.org/iqb/v99/sc/', Mehrfachauswahl, Zeige nur erste Ebene, Dialogbox | w6 |

: {tbl-colwidths="[15,15,55,15]"}

